#!perl
use strict;
# use warnings fatal => 'all';

=head1 NAME

  Workplanning

=cut

our ($html, %FORM, $db, %conf, $admin, %lang);

use Workplanning::db::Workplanning;
use Admins;
use Users;
use Address;
use Control::Address_mng;
use Msgs;
use Data::Dumper;

my $Workplanning = Workplanning->works_new($db, $admin, \%conf);
my $Admins = Admins->new($db, \%conf);
my $Users = Users->new($db, $admin, \%conf);
my $Address = Address->new($db, $admin, \%conf);
my $Msgs = Msgs->new($db, $admin, \%conf);

# use Storage;
# my $Storage = Storage->new( $db, $admin, \%conf );


my @arr_status_option = ($lang{OPT_OPEN}, $lang{NOT_ACCOMPLISHED}, $lang{ACCOMPLISHED}, $lang{POSTPONED});
my @priority = ($lang{VERY_LOW}, $lang{LOW}, $lang{NORMAL}, $lang{HIGH}, $lang{VERY_HIGH});

#**********************************************************

=head2 work_planning_add() - add work

=cut

#**********************************************************

sub work_planning_add {

 my %TEMPLATE_ARGS = ();
 $TEMPLATE_ARGS{DATE_OF_EXECUTION} = $html->form_datepicker("DATE_OF_EXECUTION", $DATE);

  if ($FORM{add}) {
    $Workplanning->works_add({ %FORM, BUILDS_ID => $FORM{LOCATION_ID}});

    $html->message("info", $lang{ADD_MASSAGE}, $lang{OPERATION});
  }
  if ($FORM{del} && $FORM{COMMENTS}) {

    $Workplanning->works_del({ID => $FORM{del}, COMMENTS => $FORM{COMMENTS}});

    $html->message("info", $lang{DELETE_MASSAGE}, $lang{OPERATION});
  }

  if ($FORM{change}) {
    $Workplanning->works_change({ %FORM, BUILDS_ID => $FORM{LOCATION_ID}});

    $html->message("info", $lang{CHANGE_MASSAGE}, $lang{OPERATION});
  }

  my $builds_list = $Address->address_list({ COLS_NAME => 1});
  if($Workplanning->{errno}){
    $html->message("err", $lang{ERROR}, $lang{NOTABLES});
    return 1;
  }
  

  $TEMPLATE_ARGS{WORKPLANNING_INSTALLATION_SEARCH} = $html->tpl_show(_include('workplanning_subscriber_search_form', "Workplanning"), 
  {SEARCH => work_planning_usr_search()},
      {OUTPUT2RETURN => 1 }
  );
  if($FORM{MSG_WORKPLANNING}){

    $TEMPLATE_ARGS{SUBMIT_BTN_NAME} = "add";
    $TEMPLATE_ARGS{SUBMIT_BTN_ACTION} = $lang{ADD};

    my $Msgs_list = $Msgs->messages_list(
      { 
        COLS_NAME => 1,
        PRIORITY_ID => "_SHOW",
        MSG_ID => $FORM{MSG_WORKPLANNING}
      }
    );
    
    foreach my $item (@$Msgs_list) {
      
      $TEMPLATE_ARGS{RESPONSIBLE_SELECT} = $html->form_select(
        'AID',
        {
          SELECTED => $item->{aid},
          SEL_LIST => $Admins->list({ MODULE => 'Admins', COLS_NAME => 1 }),
          SEL_KEY  => 'aid',
          SEL_VALUE=> 'name',
          NO_ID => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );
      $TEMPLATE_ARGS{STATUS_SELECT} = $html->form_select(
        'STATUS',
        {
          SELECTED => 0,
          SEL_ARRAY => \@arr_status_option,
          ARRAY_NUM_ID  => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );
      $TEMPLATE_ARGS{PRIORITY_SELECT} = $html->form_select(
        'PRIORITY',
        {
          SELECTED => $item->{priority_id},
          SEL_ARRAY => \@priority,
          ARRAY_NUM_ID  => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );
      $TEMPLATE_ARGS{BUILDS} = $html->tpl_show(templates('form_address_sel'), { FLAT_CHECK_FREE => 0, FLAT_CHECK_OCCUPIED => 0 }, { OUTPUT2RETURN => 1, ID => 'form_address_sel' });
      $TEMPLATE_ARGS{CREATOR} = $admin->{AID};
      $TEMPLATE_ARGS{DESCRIPTION} = $item->{subject};
      $TEMPLATE_ARGS{SUBSCRIBER} = $item->{user_name};
      $TEMPLATE_ARGS{UID} = $item->{uid};
      $TEMPLATE_ARGS{MSGS_ID} = $FORM{MSG_WORKPLANNING};
      $TEMPLATE_ARGS{DATE_OF_CREATION} = $DATE;
    }
  }
  elsif ($FORM{chg}) {

    $TEMPLATE_ARGS{SUBMIT_BTN_NAME} = "change";
    $TEMPLATE_ARGS{SUBMIT_BTN_ACTION} = $lang{CHANGE};

    my $workplanning_list = $Workplanning->works_list({ COLS_NAME => 1, ID => $FORM{chg} });
    foreach my $item (@$workplanning_list) {

      $TEMPLATE_ARGS{RESPONSIBLE_SELECT} = $html->form_select(
        'AID',
        {
          SELECTED => $item->{aid},
          SEL_LIST => $Admins->list({ MODULE => 'Admins', COLS_NAME => 1 }),
          SEL_KEY  => 'aid',
          SEL_VALUE=> 'name',
          NO_ID => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );
      
      my $user_login;
      my $users_list = $Users->list({ MODULE => 'Users', COLS_NAME => 1, UID => $item->{uid} });
      foreach my $user_name (@$users_list) {
        $user_login = $user_name->{login};
      }
      $TEMPLATE_ARGS{PRIORITY} = $item->{priority};
      $TEMPLATE_ARGS{STATUS_SELECT} = $html->form_select(
        'STATUS',
        {
          SELECTED => $item->{status},
          SEL_ARRAY => \@arr_status_option,
          ARRAY_NUM_ID  => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );

      $TEMPLATE_ARGS{PRIORITY_SELECT} = $html->form_select(
        'PRIORITY',
        {
          SELECTED => $item->{priority},
          SEL_ARRAY => \@priority,
          ARRAY_NUM_ID  => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );

      $TEMPLATE_ARGS{DATE_OF_EXECUTION} = $html->form_datepicker("DATE_OF_EXECUTION", $item->{date_of_execution});

      foreach my $builds_item (@$builds_list) {
        if($builds_item->{BUILD_ID} == $item->{builds_id})
        {
            $TEMPLATE_ARGS{BUILDS} = $html->tpl_show(templates('form_address_sel'), 
              { 
                FLAT_CHECK_FREE => 0, 
                FLAT_CHECK_OCCUPIED => 0, 
                ADDRESS_DISTRICT => $builds_item->{DISTRICT_NAME}, 
                DISTRICT_ID => $builds_item->{DISTRICT_ID}, 
                ADDRESS_STREET => $builds_item->{STREET_NAME}, 
                STREET_ID => $builds_item->{STREET_ID}, 
                ADDRESS_BUILD => $builds_item->{BUILD_NAME},
                LOCATION_ID => $builds_item->{BUILD_ID}
              }, 
              { 
                OUTPUT2RETURN => 1,
                ID => 'form_address_sel'
              }
            );
          }
        }
      $TEMPLATE_ARGS{ID} = $FORM{chg};
      $TEMPLATE_ARGS{DATE_OF_CREATION} = $item->{date_of_creation};
      $TEMPLATE_ARGS{CREATOR} = $admin->{AID};
      $TEMPLATE_ARGS{DESCRIPTION} = $item->{description};
      $TEMPLATE_ARGS{BUDGET} = $item->{budget};
      $TEMPLATE_ARGS{COMMENT} = $item->{comment};
      $TEMPLATE_ARGS{SUBSCRIBER} = $user_login;
      $TEMPLATE_ARGS{UID} = $item->{uid};
      $TEMPLATE_ARGS{MSGS_ID} = $item->{msgs_id};

    }
  }
  elsif(!$FORM{chg} && !$FORM{MSG_WORKPLANNING}){

    $TEMPLATE_ARGS{SUBMIT_BTN_NAME} = "add";
    $TEMPLATE_ARGS{SUBMIT_BTN_ACTION} = $lang{ADD};
    
    my $admins_list = $Admins->list({ MODULE => 'Admins', COLS_NAME => 1 });

    $TEMPLATE_ARGS{RESPONSIBLE_SELECT} = $html->form_select(
      'AID',
      {
        SEL_LIST => $admins_list,
        SEL_KEY  => 'aid',
        SEL_VALUE=> 'name',
        NO_ID => 1,
        SEL_OPTIONS => {"" => ""}
      }
    );

    $TEMPLATE_ARGS{STATUS_SELECT} = $html->form_select(
      'STATUS',
      {
        SEL_ARRAY => \@arr_status_option,
        ARRAY_NUM_ID  => 1,
        SEL_OPTIONS => {"" => ""}
      }
    );

    $TEMPLATE_ARGS{PRIORITY_SELECT} = $html->form_select(
      'PRIORITY',
      {
        SEL_ARRAY => \@priority,
        ARRAY_NUM_ID  => 1,
        SEL_OPTIONS => {"" => ""}
      }
    );

    if($FORM{user_search_form}==1){
      return 1;
    }
    $TEMPLATE_ARGS{BUILDS} = $html->tpl_show(templates('form_address_sel'), { FLAT_CHECK_FREE => 0, FLAT_CHECK_OCCUPIED => 0 }, { OUTPUT2RETURN => 1, ID => 'form_address_sel' });
    $TEMPLATE_ARGS{CREATOR} = $admin->{AID};
    $TEMPLATE_ARGS{DATE_OF_CREATION} = $DATE;
  }
  $html->tpl_show(
        _include("workplanning_add_form", "Workplanning"),
        {
          %TEMPLATE_ARGS,
        }
      );

  my $workplanning_list = $Workplanning->works_list({ COLS_NAME => 1, DESC => "desc" });
  my $workplanning_works = $html->table(
    {
      width   => "100%",
      caption => $lang{WORK_REPORT},
      title   => [ "ID", $lang{DATE_OF_CREATION}, $lang{DATE_OF_EXECUTION}, $lang{RESPONSIBLE}, $lang{DESCRIPTION}, $lang{STATUS}, $lang{PRIORITY},"$lang{BUDGET}" . ' $', $lang{SUBSCRIBER}, $lang{LOCATION}, $lang{COMMENT}, $lang{CREATOR}, "Привязка", "" ],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      MENU    => "$lang{SEARCH}:index=" . get_function_index('work_planning') . "&$pages_qs:search",
      export  => 1
    }
  );

  foreach my $item (@$workplanning_list) {
    $Users->pi({ UID => $item->{uid} });
    my $msgs_indicator = ($item->{msgs_id}) ? $lang{YES} : $lang{NO};
    my $build_name = $Address->build_info({ ID => $item->{builds_id} });
    my $admin_name  = ($Admins->info($item->{aid}))->{A_FIO};
    
    my $del_button  = $html->button("", "index=$index&del=$item->{id}", { class => "del", MESSAGE => "$lang{DEL} $item->{description}", });
    my $edit_button = $html->button("", "index=$index&chg=$item->{id}", { class => "", ADD_ICON => "glyphicon glyphicon-pencil" });
    $workplanning_works->addrow(
      $item->{id},     $item->{date_of_creation}, $item->{date_of_execution},    $admin_name,            $item->{description},                     $arr_status_option[ $item->{status} ],    @priority[ $item->{priority} ],
      $item->{budget}, $Users->{FIO},             $build_name->{NUMBER},         $item->{comment},       $Admins->info($item->{creator})->{A_FIO}, $msgs_indicator, "$edit_button$del_button"
    );
  }
  print $workplanning_works->show();
}

#**********************************************************
=head2 work_planning() - planning work

=cut
#**********************************************************
sub work_planning {
  my $date_of_execution = $html->form_daterangepicker({ NAME => "DATE_OF_EXECUTION", FORM_NAME => "DATE_OF_EXECUTION"});
  my $date_of_creation = $html->form_daterangepicker({ NAME => "DATE_OF_CREATION", FORM_NAME => "DATE_OF_CREATION"});
  my $Admins_aid_list = $Admins->list({ COLS_NAME => 1 });
  my $admins_option;
  my $status_option;
  my $admin_name;

  my $responsible_select = $html->form_select(
    'RESPONSIBLE',
    {
      SELECTED => $FORM{RESPONSIBLE},
      SEL_LIST => $Admins->list({ MODULE => 'Admins', COLS_NAME => 1 }),
      SEL_KEY  => 'aid',
      SEL_VALUE=> 'name',
      NO_ID => 1,
      SEL_OPTIONS => {"" => ""}
    }
  );

  my $status_select = $html->form_select(
    'STATUS',
    {
      SELECTED => $FORM{STATUS},
      SEL_ARRAY => \@arr_status_option,
      ARRAY_NUM_ID  => 1,
      SEL_OPTIONS => {"" => ""}
    }
  );

  $html->tpl_show(
    _include("workplanning_reports", "Workplanning"),
    {
      DATE_OF_CREATION  => $date_of_creation,
      DATE_OF_EXECUTION => $date_of_execution,
      STATUS_SELECT     => $status_select,
      RESPONSIBLE_SELECT=> $responsible_select,
    }
  );

  my $workplanning_list = $Workplanning->works_list(
    { 
      COLS_NAME => 1, 
      DESC => "desc", 
      DATE_OF_CREATION => $FORM{DATE_OF_CREATION}, 
      DATE_OF_EXECUTION => $FORM{DATE_OF_EXECUTION}, 
      STATUS => $FORM{STATUS},
      AID => $FORM{RESPONSIBLE},
    }
  );
  if($Workplanning->{errno}){
    $html->message("err", $lang{ERROR}, $lang{NOTABLES});
    return 1;
  }
  my $workplanning_works = $html->table(
    {
      width   => "100%",
      caption => $lang{WORK_REPORT},
      title   => [ "ID", $lang{DATE_OF_CREATION}, $lang{DATE_OF_EXECUTION}, $lang{RESPONSIBLE}, $lang{DESCRIPTION}, $lang{STATUS}, "$lang{BUDGET}" . ' $', $lang{SUBSCRIBER}, $lang{LOCATION}, $lang{COMMENT}, $lang{CREATOR}],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      MENU    => "$lang{ADD}:index=" . get_function_index('work_planning_add') . "&add_form=1&$pages_qs:add",
      export  => 1
    }
  );

  foreach my $item (@$workplanning_list) {

    $Users->pi({ UID => $item->{uid} });
    my $build_name = $Address->build_info({ ID => $item->{builds_id} });

    my $admin_name = $Admins->info($item->{aid});
    $workplanning_works->addrow(
      $item->{id},     $item->{date_of_creation}, $item->{date_of_execution},     "$admin_name->{A_FIO}", $item->{description},                     $arr_status_option[ $item->{status} ],
      $item->{budget}, $Users->{FIO},             $build_name->{NUMBER}, $item->{comment},       $Admins->info($item->{creator})->{A_FIO}
    );
  }

  print $workplanning_works->show();
}

#**********************************************************
=head2 work_planning_usr_search()

  Returns:
    HTML code of button to open modal search

=cut
#**********************************************************
sub work_planning_usr_search{
  my ($attr) = @_;
  if ( $FORM{user_search_form} ) {
    # First step : Show search form
    if ( $FORM{user_search_form} == 1 ) {
      #      my $address_form = $html->tpl_show( templates('form_address_search'), undef, {OUTPUT2RETURN => 1});
      my $search_form = $html->tpl_show( _include( 'workplanning_user_search', 'Workplanning' ), {
          ADDRESS_FORM => $html->tpl_show( templates('form_address_search'), undef, { OUTPUT2RETURN => 1 })
        }, { OUTPUT2RETURN => 1 } );
      
      $html->tpl_show( templates( 'form_popup_window' ),
        {
          SUB_TEMPLATE     => $search_form,
          CALLBACK_FN_NAME => 'storage_main'
        }
      );
      return 2;
    }
    # Second step: show results
    elsif ( $FORM{user_search_form} == 2 ) {
      my $script = "<script>defineSearchResultLogic()</script>";
      my $users_list = $users->list(
        {
          %FORM,
          FIO       => "*$FORM{FIO}*",
          PHONE     => '*',
          COLS_NAME => 1
        }
      );
      
      if ( _error_show( $users ) || !defined $users_list ) {
        $html->message( "err", $lang{ERROR}, "$lang{USER}: $lang{NOT_EXIST}" );
        return 2;
      }
      
      if ( scalar @{$users_list} > 40 ) {
        $html->message( "warn", $lang{ERROR}, $lang{ERR_SEARCH_VAL_TOSMALL} );
        return 2;
      }
      
      my $workplanning_works = $html->table(
        {
          width   => '100%',
          caption => "$lang{USERS}",
          title   => [ "$lang{LOGIN}", "$lang{FIO}", "$lang{PHONE}" ],
          qs      => $pages_qs,
          ID      => 'SEARCH_TABLE_ID'
        }
      );
      foreach my $user ( @{$users_list} ) {
        my $login_str = "<button class='btn btn-default search-result' data-uid='$user->{uid}'>$user->{login}</button>";
        $workplanning_works->addrow(
          $login_str,
          $user->{fio} || '--',
          $user->{phone} || '--'
        );
      }
      
      print $workplanning_works->show() . $script;
      return 2;
    }
  }
  
  my $search_button = $html->button( '', '', {
      NO_LINK_FORMER => 1,
      JAVASCRIPT     => 1,
      SKIP_HREF      => 1,
      ex_params      =>
      qq{onclick="loadRawToModal('?qindex=$index&install_accountability=1&header=2&user_search_form=1')"},
      class          => 'btn btn-defaut',
      ICON           => 'glyphicon glyphicon-search'
    } );
  
  # if ( $Storage->{UID} ) {
  #   $users->info( $Storage->{UID} );
  # };
  
  if ( $attr->{NUMERIC} ) {
    return 1;
  }
  
  return $search_button;
}
