#!perl

=head1 NAME

  Workplanning

=cut

our ($html, %FORM, $db, %conf, $admin, %lang);

use Workplanning::db::Workplanning;
my $Workplanning = Workplanning->new($db, $admin, \%conf);
use Admins;
my $Admins = Admins->new($db, \%conf);
use Users;
my $Users = Users->new($db, $admin, \%conf);
use Address;
my $Address = Address->new($db, $admin, \%conf);
use Control::Address_mng;
use Storage;
my $Storage = Storage->new( $db, $admin, \%conf );

use Data::Dumper;
use strict;

my @arr_status_option = ($lang{OPT_OPEN}, $lang{NOT_ACCOMPLISHED}, $lang{ACCOMPLISHED}, $lang{POSTPONED});

#**********************************************************

=head2 work_planning() - planning work

=cut

#**********************************************************

sub work_planning_add {
  my $datepicker = $html->form_datepicker("DATE_OF_EXECUTION", $DATE);
  if ($FORM{ACTION} && $FORM{ACTION} eq 'ADD') {
    $Workplanning->add({ %FORM, BUILDS_ID => $FORM{ADDRESS_BUILD}, SUBSCRIBER => $FORM{UID}});

    $html->message("info", $lang{ADD_MASSAGE}, $lang{OPERATION});
  }
  if ($FORM{DELETE}) {
    $Workplanning->del($FORM{DELETE});

    $html->message("info", $lang{DELETE_MASSAGE}, $lang{OPERATION});
  }
  if ($FORM{ACTION} && $FORM{ACTION} eq 'CHANGE') {
    $Workplanning->change({ %FORM, BUILDS_ID => $FORM{LOCATION_ID}, });

    $html->message("info", $lang{CHANGE_MASSAGE}, $lang{OPERATION});
  }

  my $Builds_list = $Address->address_list({ COLS_NAME => 1});

  my $builds; 

  if ($FORM{EDIT}) {

    my $Workplanning_list = $Workplanning->list({ COLS_NAME => 1, ID => $FORM{EDIT} });

    foreach my $item (@$Workplanning_list) {

      foreach my $builds_item (@$Builds_list) {
        if($builds_item->{BUILD_ID} == $item->{builds_id})
        {
            $builds = $html->tpl_show(templates('form_address_sel'), 
              { 
                FLAT_CHECK_FREE => 0, 
                FLAT_CHECK_OCCUPIED => 0, 
                DISTRICT_ID => $builds_item->{DISTRICT_ID}, 
                ADDRESS_STREET => $builds_item->{STREET_NAME}, 
                ADDRESS_BUILD => $builds_item->{BUILD_NAME}}, 
              { 
                OUTPUT2RETURN => 1,
                ID => 'form_address_sel'
              }
            );
          }
        }

      my $responsible_select = $html->form_select(
        'AID',
        {
          SELECTED => $item->{aid},
          SEL_LIST => $Admins->list({ MODULE => 'Admins', COLS_NAME => 1 }),
          SEL_KEY  => 'aid',
          SEL_VALUE=> 'name',
          NO_ID => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );

      # my $subscriber_select = $html->form_select(
      #   'SUBSCRIBER',
      #   {
      #     SELECTED => $item->{subscriber},
      #     SEL_LIST => $Users->list({ MODULE => 'Users', COLS_NAME => 1 }),
      #     SEL_KEY  => 'uid',
      #     SEL_VALUE=> 'login',
      #     NO_ID => 1,
      #     SEL_OPTIONS => {"" => ""}
      #   }
      # );
      
      my $user_login;
      my $Users_list = $Users->list({ MODULE => 'Users', COLS_NAME => 1, UID => $item->{subscriber} });
      foreach my $user_name (@$Users_list) {
        $user_login = $user_name->{login};
      }

      my $status_select = $html->form_select(
        'STATUS',
        {
          SELECTED => $item->{status},
          SEL_ARRAY => \@arr_status_option,
          ARRAY_NUM_ID  => 1,
          SEL_OPTIONS => {"" => ""}
        }
      );

      $datepicker = $html->form_datepicker("DATE_OF_EXECUTION", $item->{date_of_execution});
      my $subscriber_search = $html->tpl_show(_include('workplanning_subscriber_search_form', "Workplanning"), { SEARCH => storage_installation_search()}, {OUTPUT2RETURN => 1 });
      if($FORM{user_search_form}==1){
        return 1;
      }
      $html->tpl_show(
        _include("workplanning_add_form", "Workplanning"),
        {
          ID                => $FORM{EDIT},
          SUBMIT_BTN_ACTION => "ADD",
          DATE_OF_CREATION  => $item->{date_of_creation},
          CREATOR           => $admin->{AID},
          DATE_OF_EXECUTION => $datepicker,
          RESPONSIBLE_SELECT=> $responsible_select,
          STATUS_SELECT     => $status_select,
          #SUBSCRIBER_SELECT => $subscriber_select,
          BUILDS            => $builds,
          DESCRIPTION       => $item->{description},
          BUDGET            => $item->{budget},
          COMMENT           => $item->{comment},
          SUBMIT_BTN_ACTION => $lang{CHANGE},
          ACTION            => 'CHANGE',
          SUBSCRIBER               => $user_login,
          STORAGE_INSTALLATION_SEARCH => $subscriber_search
        }
      );
    }
  }
  else{
    $builds = $html->tpl_show(templates('form_address_sel'), { FLAT_CHECK_FREE => 0, FLAT_CHECK_OCCUPIED => 0 }, { OUTPUT2RETURN => 1, ID => 'form_address_sel' });

    my $admins_list = $Admins->list({ MODULE => 'Admins', COLS_NAME => 1 });

    my $responsible_select = $html->form_select(
      'AID',
      {
        SEL_LIST => $admins_list,
        SEL_KEY  => 'aid',
        SEL_VALUE=> 'name',
        NO_ID => 1,
        SEL_OPTIONS => {"" => ""}
      }
    );

    # my $subscriber_select = $html->form_select(
    #   'SUBSCRIBER',
    #   {
    #     SEL_LIST => $Users->list({ MODULE => 'Users', COLS_NAME => 1 }),
    #     SEL_KEY  => 'uid',
    #     SEL_VALUE=> 'login',
    #     NO_ID => 1,
    #     SEL_OPTIONS => {"" => ""}
    #   }
    # );

    my $status_select = $html->form_select(
      'STATUS',
      {
        SEL_ARRAY => \@arr_status_option,
        ARRAY_NUM_ID  => 1,
        SEL_OPTIONS => {"" => ""}
      }
    );
    my $subscriber_search = $html->tpl_show(_include('workplanning_subscriber_search_form', "Workplanning"), { SEARCH => storage_installation_search()}, {OUTPUT2RETURN => 1 });
    if($FORM{user_search_form}==1){
      return 1;
    }
    $html->tpl_show(
      _include("workplanning_add_form", "Workplanning"),
      {
        DATE_OF_EXECUTION => $datepicker,
        CREATOR           => $admin->{AID},
        DATE_OF_CREATION  => $DATE,
        RESPONSIBLE_SELECT=> $responsible_select,
        STATUS_SELECT     => $status_select,
        #SUBSCRIBER_SELECT => $subscriber_select,
        BUILDS            => $builds,
        SUBMIT_BTN_ACTION => $lang{ADD},
        ACTION            => 'ADD',
        STORAGE_INSTALLATION_SEARCH => $subscriber_search
      }
    );
  }

  my $Workplanning_list = $Workplanning->list({ COLS_NAME => 1, DESC => "desc" });
  my $table = $html->table(
    {
      width   => "100%",
      caption => $lang{WORK_REPORT},
      title   => [ "ID", $lang{DATE_OF_CREATION}, $lang{DATE_OF_EXECUTION}, $lang{RESPONSIBLE}, $lang{DESCRIPTION}, $lang{STATUS}, "$lang{BUDGET}" . ' $', $lang{SUBSCRIBER}, $lang{LOCATION}, $lang{COMMENT}, $lang{CREATOR}, "" ],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      MENU    => "$lang{SEARCH}:index=" . get_function_index('work_planning') . "&$pages_qs:search",
      export  => 1
    }
  );
  foreach my $item (@$Workplanning_list) {
    $Users->pi({ UID => $item->{subscriber} });
    my $build_name = $Address->address_list({ ID => $item->{builds_id} });

    my $Admin_name  = $Admins->info($item->{aid});
    my $del_button  = $html->button("", "index=$index&DELETE=$item->{id}", { class => "text-danger", ADD_ICON => "glyphicon glyphicon-trash" });
    my $edit_button = $html->button("", "index=$index&EDIT=$item->{id}", { class => "", ADD_ICON => "glyphicon glyphicon-pencil" });
    $table->addrow(
      $item->{id},     $item->{date_of_creation}, $item->{date_of_execution},     "$Admin_name->{A_FIO}", $item->{description},                     $arr_status_option[ $item->{status} ],
      $item->{budget}, $Users->{FIO},             $build_name->[0]->{BUILD_NAME}, $item->{comment},       $Admins->info($item->{creator})->{A_FIO}, "$edit_button$del_button"
    );
  }
  print $table->show();
}

#**********************************************************

=head2 work_planning() - planning work

=cut

#**********************************************************

sub work_planning {
  my $date_of_execution = $html->form_daterangepicker({ NAME => "DATE_OF_EXECUTION", FORM_NAME => "DATE_OF_EXECUTION"});
  my $date_of_creation = $html->form_daterangepicker({ NAME => "DATE_OF_CREATION", FORM_NAME => "DATE_OF_CREATION"});
  my $Admins_aid_list = $Admins->list({ COLS_NAME => 1 });
  my $admins_option;
  my $status_option;
  my $admin_name;

  my $responsible_select = $html->form_select(
    'RESPONSIBLE',
    {
      SELECTED => $FORM{RESPONSIBLE},
      SEL_LIST => $Admins->list({ MODULE => 'Admins', COLS_NAME => 1 }),
      SEL_KEY  => 'aid',
      SEL_VALUE=> 'name',
      NO_ID => 1,
      SEL_OPTIONS => {"" => ""}
    }
  );

  my $status_select = $html->form_select(
    'STATUS',
    {
      SELECTED => $FORM{STATUS},
      SEL_ARRAY => \@arr_status_option,
      ARRAY_NUM_ID  => 1,
      SEL_OPTIONS => {"" => ""}
    }
  );

  $html->tpl_show(
    _include("workplanning_reports", "Workplanning"),
    {
      DATE_OF_CREATION  => $date_of_creation,
      DATE_OF_EXECUTION => $date_of_execution,
      STATUS_SELECT     => $status_select,
      RESPONSIBLE_SELECT=> $responsible_select,
    }
  );
  my $Workplanning_list = $Workplanning->list(
    { 
      COLS_NAME => 1, 
      DESC => "desc", 
      DATE_OF_CREATION => $FORM{DATE_OF_CREATION}, 
      DATE_OF_EXECUTION => $FORM{DATE_OF_EXECUTION}, 
      STATUS => $FORM{STATUS},
      AID => $FORM{RESPONSIBLE},
    }
  );
  my $table = $html->table(
    {
      width   => "100%",
      caption => $lang{WORK_REPORT},
      title   => [ "ID", $lang{DATE_OF_CREATION}, $lang{DATE_OF_EXECUTION}, $lang{RESPONSIBLE}, $lang{DESCRIPTION}, $lang{STATUS}, "$lang{BUDGET}" . ' $', $lang{SUBSCRIBER}, $lang{LOCATION}, $lang{COMMENT}, $lang{CREATOR}],
      qs      => $pages_qs,
      ID      => "TABLE_ID",
      MENU    => "$lang{ADD}:index=" . get_function_index('work_planning_add') . "&add_form=1&$pages_qs:add",
      export  => 1
    }
  );
  foreach my $item (@$Workplanning_list) {

    $Users->pi({ UID => $item->{subscriber} });
    my $build_name = $Address->address_list({ ID => $item->{builds_id} });

    my $Admin_name  = $Admins->info($item->{aid});
    $table->addrow(
      $item->{id},     $item->{date_of_creation}, $item->{date_of_execution},     "$Admin_name->{A_FIO}", $item->{description},                     $arr_status_option[ $item->{status} ],
      $item->{budget}, $Users->{FIO},             $build_name->[0]->{BUILD_NAME}, $item->{comment},       $Admins->info($item->{creator})->{A_FIO}
    );
  }

  print $table->show();
}

#**********************************************************
=head2 storage_installation_search()

  Returns:
    HTML code of button to open modal search

=cut
#**********************************************************
sub storage_installation_search{
  my ($attr) = @_;
  if ( $FORM{user_search_form} ) {
    # First step : Show search form
    if ( $FORM{user_search_form} == 1 ) {
      #      my $address_form = $html->tpl_show( templates('form_address_search'), undef, {OUTPUT2RETURN => 1});
      my $search_form = $html->tpl_show( _include( 'storage_user_search', 'Storage' ), {
          ADDRESS_FORM => $html->tpl_show( templates('form_address_search'), undef, { OUTPUT2RETURN => 1 })
        }, { OUTPUT2RETURN => 1 } );
      
      $html->tpl_show( templates( 'form_popup_window' ),
        {
          SUB_TEMPLATE     => $search_form,
          CALLBACK_FN_NAME => 'storage_main'
        }
      );
      return 2;
    }
    # Second step: show results
    elsif ( $FORM{user_search_form} == 2 ) {
      my $script = "<script>defineSearchResultLogic()</script>";
      my $users_list = $users->list(
        {
          %FORM,
          FIO       => "*$FORM{FIO}*",
          PHONE     => '*',
          COLS_NAME => 1
        }
      );
      
      if ( _error_show( $users ) || !defined $users_list ) {
        $html->message( "err", $lang{ERROR}, "$lang{USER}: $lang{NOT_EXIST}" );
        return 2;
      }
      
      if ( scalar @{$users_list} > 40 ) {
        $html->message( "warn", $lang{ERROR}, $lang{ERR_SEARCH_VAL_TOSMALL} );
        return 2;
      }
      
      my $table = $html->table(
        {
          width   => '100%',
          caption => "$lang{USERS}",
          title   => [ "$lang{LOGIN}", "$lang{FIO}", "$lang{PHONE}" ],
          qs      => $pages_qs,
          ID      => 'SEARCH_TABLE_ID'
        }
      );
      foreach my $user ( @{$users_list} ) {
        my $login_str = "<button class='btn btn-default search-result' data-uid='$user->{uid}'>$user->{login}</button>";
        $table->addrow(
          $login_str,
          $user->{fio} || '--',
          $user->{phone} || '--'
        );
      }
      
      print $table->show() . $script;
      return 2;
    }
  }
  
  my $search_button = $html->button( '', '', {
      NO_LINK_FORMER => 1,
      JAVASCRIPT     => 1,
      SKIP_HREF      => 1,
      ex_params      =>
      qq{onclick="loadRawToModal('?qindex=$index&install_accountability=1&header=2&user_search_form=1')"},
      class          => 'btn btn-defaut',
      ICON           => 'glyphicon glyphicon-search'
    } );
  
  if ( $Storage->{UID} ) {
    $users->info( $Storage->{UID} );
  };
  
  if ( $attr->{NUMERIC} ) {
    return 1;
  }
  
  return $search_button;
}
