CREATE TABLE IF NOT EXISTS `work_planning` ( 
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, 
	`date_of_creation` DATE NOT NULL DEFAULT '0000-00-00',
	`date_of_execution` DATE NOT NULL DEFAULT '0000-00-00',
	`aid` SMALLINT(1) NOT NULL DEFAULT 0, 
	`description` VARCHAR(255) DEFAULT '',
	`status` SMALLINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`budget` FLOAT(24) UNSIGNED NOT NULL DEFAULT 0,
	`uid` SMALLINT(1) NOT NULL DEFAULT 0,
	`builds_id` SMALLINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`comment` VARCHAR(60) DEFAULT '',
	`creator` SMALLINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
)
COMMENT = 'Work planning';
